[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "cicd-automation"
dynamic = ["version"]
requires-python = ">=3.12"
dependencies = [

]
