[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "monorepo2"
requires-python = ">=3.12"
dynamic = ["version"]
description = "This is a python monorepo for testing"
dependencies = [

]
