[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "monorepo1"
dynamic = ["version"]
requires-python = ">=3.12"
description = "This is a python monorepo1 for testing"
dependencies = [

]
