name: build-workflow
run-name: Build Workflow

on:
  push:

jobs:
    build:
        name: "Python Build"
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ["3.12"]

        steps:
        -   id: checkout
            name: Checkout
            uses: actions/checkout@v5

        -   id: setup-python
            name: Set up Python ${{ matrix.python-version }}
            uses: actions/setup-python@v5
            with:
                python-version: ${{ matrix.python-version }}

        -   id: display-version
            name: Display Python version
            run: python -c "import sys; print(sys.version)"

        -   id: setup-pip
            name: Virtual Environment and Build + Install
            run: |
                python -m venv python_venv
                source python_venv/bin/activate && echo "The virtual env path is $VIRTUAL_ENV"
                python -m pip install --upgrade pip
                python -m pip install -r $GITHUB_WORKSPACE/requirements.txt

        -   id: setup-uv
            uses: astral-sh/setup-uv@v6
            with:
                version: "latest"
        -   id: display-uv-version
            name: Display uv version
            run: uv --version
