name: build-workflow
run-name: Build Workflow

on:
  push:

permissions:
    contents: read

jobs:
    build:
        name: "Python Build"
        runs-on: ubuntu-latest

        steps:
        -   id: checkout
            name: Checkout
            uses: actions/checkout@v5
            with:
                fetch-depth: 0

        -   id: setup-python
            name: Set up Python 3.12
            uses: actions/setup-python@v5
            with:
                python-version: "3.12.x"

        -   id: display-version
            name: Display Python version
            run: python -c "import sys; print(sys.version)"

        -   id: setup-uv
            uses: astral-sh/setup-uv@v6
            with:
                version: "latest"

        -   id: display-uv-version
            name: Display uv version
            run: uv --version

        -   id: uv-build
            name: uv virtual environment, build and install
            run: |
                echo "Running uv sync for installing all packages in virutal environment from pyproject.toml file"
                uv sync

                echo "Falling back to requirements.txt if not present in pyproject.toml"
                uv add -r requirements.txt

                echo "Running uv build for creating whl files"
                uv build

        -   id: get-changed-files
            name: Get Changed Files
            run: |
                temp=$(git diff --name-only "${{ github.event.before }}" "${{ github.sha }}")
                
                # MONOREPO1=false
                # MONOREPO2=false
                repos_changed=()
                for FILE in $temp; do
                    if [[ "$FILE" == src/* ]]; then
                        # MONOREPO1=true
                        IFS='/'; arrIN=($FILE); unset IFS;
                        repos_changed+=( ${arrIN[1]} )
                    fi
                done

                echo "REPOS_CHANGED=$repos_changed" >> $GITHUB_ENV

        -   id: install-packages
            name: Install essential Packages
            run: |
                python -m venv python_venv
                source python_venv/bin/activate
                echo "Virtual Environment Created"
                python -m pip install build

        -   id: build-individual-projects
            name: Build Projects
            run: |
                echo "${{ env.REPOS_CHANGED }}"
                source python_venv/bin/activate
                for REPO in ${{ env.REPOS_CHANGED }}; do
                    echo "$REPO"
                    cd src/$REPO
                    python -m build
                    cd ..
                    echo "$(REPO) Built successfully"
                done
